version: "3.9"

services:
  angular16_client:
    container_name: angular16_client
    build:  
      context: ./angular16-client
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - node_api_service
    networks:
      - app-challenger-network

  node_api_service:
    container_name: node_api_service
    build:  
      context: ./node-api-service
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PG_DB=node_live_pg_db
      - PG_USER=fxnetworks
      - PG_PASSWORD=12345
      - PG_HOST=node_pg_db
    depends_on:
      - node_pg_db
    networks:
      - app-challenger-network

  node_pg_db:
    container_name: node_pg_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_pg_db
      - POSTGRES_USER=fxnetworks
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_pg_db_data:/var/lib/postgresql/data
    networks:
      - app-challenger-network

volumes:
  node_pg_db_data: {}

networks:
  app-challenger-network:
    driver: bridge